        @echo off
        echo €ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ€
        echo €                                       €
        echo €     Assembling Spectrum Wild FDD      €
        echo €            By Entire Group            €
        echo €                                       €
        echo €‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€


..\ASAM\ASAM.EXE wildfddx.ac5 c51.cmd



